server {
    listen 80;
    server_name localhost;

    # 1. Проксирование всех запросов к API на FastAPI бэкенд
    location /api/ {
        proxy_pass http://172.17.0.1:8000; # ИСПРАВЛЕНО: Прямой защищенный мост к бэкенду
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # 2. Заглушка или раздача собранного React-фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}